#!/bin/bash 

read -p "Please enter a URL of an image file you like:" URL
curl "$URL" > file
aws s3 cp file s3://ds2002-npj4qa-2/
aws s3 ls s3://ds2002-npj4qa-2/
aws s3 presign --expires-in 604800 s3://ds2002-npj4qa-2/file
